/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Banco.FuncoesBanco;
import java.awt.Toolkit;
import mode.bean.Administrador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mode.bean.Veiculo;
//import VELHOS.ConexaoBD;
//import VELHOS.ControleUsuario;

/**
 *
 * @author Lucas
 */
public class TelaAdmSDI extends javax.swing.JFrame {

    Administrador mod ;
    FuncoesBanco f = new FuncoesBanco();
//    ControleUsuario control = new ControleUsuario();
//    ConexaoBD conex = new ConexaoBD();
            
    public TelaAdmSDI() {
        initComponents();
        this.setTitle("SMES - StoffMalocoking Enterprise System");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Botao_Buscar = new javax.swing.JButton();
        EscolhaAtributo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Retornar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadastrarAdm = new javax.swing.JMenuItem();
        EditarAdm = new javax.swing.JMenuItem();
        ExcluirAdm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CadastarCliente = new javax.swing.JMenuItem();
        EditarCliente = new javax.swing.JMenuItem();
        ApagarCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        AdicionarVeiculo = new javax.swing.JMenuItem();
        DevolverVeiculo = new javax.swing.JMenuItem();
        ApagarVeiculo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        infor = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel4.setText("ADM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sem Título-1.png"))); // NOI18N

        TextoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoValorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busque o veículo mais adequado para você!");

        Botao_Buscar.setText("Buscar");
        Botao_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_BuscarActionPerformed(evt);
            }
        });

        EscolhaAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "Marca", "Modelo", "Cor" }));
        EscolhaAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaAtributoActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        Retornar.setText("Retornar");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });
        jMenu1.add(Retornar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMenu2.setText("Admin");

        CadastrarAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        CadastrarAdm.setText("Cadastrar");
        CadastrarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAdmActionPerformed(evt);
            }
        });
        jMenu2.add(CadastrarAdm);

        EditarAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        EditarAdm.setText("Editar");
        EditarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarAdmActionPerformed(evt);
            }
        });
        jMenu2.add(EditarAdm);

        ExcluirAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        ExcluirAdm.setText("Excluir");
        ExcluirAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirAdmActionPerformed(evt);
            }
        });
        jMenu2.add(ExcluirAdm);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        jMenu3.setText("Cliente");

        CadastarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        CadastarCliente.setText("Cadastrar");
        CadastarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(CadastarCliente);

        EditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        EditarCliente.setText("Editar");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(EditarCliente);

        ApagarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        ApagarCliente.setText("Excluir");
        ApagarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(ApagarCliente);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car.png"))); // NOI18N
        jMenu5.setText("Veículos");

        AdicionarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        AdicionarVeiculo.setText("Adicionar");
        AdicionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarVeiculoActionPerformed(evt);
            }
        });
        jMenu5.add(AdicionarVeiculo);

        DevolverVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_delete.png"))); // NOI18N
        DevolverVeiculo.setText("Devolver veículo");
        DevolverVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverVeiculoActionPerformed(evt);
            }
        });
        jMenu5.add(DevolverVeiculo);

        ApagarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_delete.png"))); // NOI18N
        ApagarVeiculo.setText("Apagar veículo");
        ApagarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarVeiculoActionPerformed(evt);
            }
        });
        jMenu5.add(ApagarVeiculo);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        jMenu4.setText("Sobre");

        infor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        infor.setText("Informações");
        infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inforActionPerformed(evt);
            }
        });
        jMenu4.add(infor);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EscolhaAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(277, 277, 277)
                            .addComponent(Botao_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EscolhaAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addComponent(Botao_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
        new TelaPrincipalSDI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetornarActionPerformed

    private void AdicionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarVeiculoActionPerformed
        new TelaCadastroVeiculoSDI().setVisible(true);
    }//GEN-LAST:event_AdicionarVeiculoActionPerformed

    private void inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inforActionPerformed
        new TelaSobreSDI().setVisible(true);
    }//GEN-LAST:event_inforActionPerformed

    private void TextoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoValorActionPerformed

    private void Botao_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_BuscarActionPerformed
        String atributo = String.valueOf(EscolhaAtributo.getSelectedItem());
        String valor = TextoValor.getText();
        ArrayList lista_de_Veiculos = f.buscarVeiculosObject(atributo, valor);
        if(lista_de_Veiculos.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "Não há veículos com essa caracterítica!");
        }else{
        new TelaPesquisaSDI(lista_de_Veiculos).setVisible(true);
        }
    }//GEN-LAST:event_Botao_BuscarActionPerformed

    private void EscolhaAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolhaAtributoActionPerformed

    private void DevolverVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverVeiculoActionPerformed
        new TelaDevolverVeiculoSDI().setVisible(true);
    }//GEN-LAST:event_DevolverVeiculoActionPerformed

    private void ApagarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarVeiculoActionPerformed
           new TelaDeletarVeiculoSDI().setVisible(true);
    }//GEN-LAST:event_ApagarVeiculoActionPerformed

    private void CadastarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastarClienteActionPerformed
        new TelaCadastroClienteSDI().setVisible(true);
    }//GEN-LAST:event_CadastarClienteActionPerformed

    private void ApagarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarClienteActionPerformed
        new TelaDeletarClienteSDI().setVisible(true);
    }//GEN-LAST:event_ApagarClienteActionPerformed

    private void EditarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarAdmActionPerformed
        new TelaEditarAdmSDI().setVisible(true);
    }//GEN-LAST:event_EditarAdmActionPerformed

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
        new TelaEditarClienteSDI().setVisible(true);
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void CadastrarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAdmActionPerformed
        new TelaCadastroAdmSDI().setVisible(true);
    }//GEN-LAST:event_CadastrarAdmActionPerformed

    private void ExcluirAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirAdmActionPerformed
        new TelaDeletarAdmSDI().setVisible(true);
    }//GEN-LAST:event_ExcluirAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarVeiculo;
    private javax.swing.JMenuItem ApagarCliente;
    private javax.swing.JMenuItem ApagarVeiculo;
    private javax.swing.JButton Botao_Buscar;
    private javax.swing.JMenuItem CadastarCliente;
    private javax.swing.JMenuItem CadastrarAdm;
    private javax.swing.JMenuItem DevolverVeiculo;
    private javax.swing.JMenuItem EditarAdm;
    private javax.swing.JMenuItem EditarCliente;
    private javax.swing.JComboBox<String> EscolhaAtributo;
    private javax.swing.JMenuItem ExcluirAdm;
    private javax.swing.JMenuItem Retornar;
    private javax.swing.JTextField TextoValor;
    private javax.swing.JMenuItem infor;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
           setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/car.png")));
    }
}
