/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Banco.FuncoesBanco;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mode.bean.Veiculo;
//import VELHOS.ConexaoBD;

/**
 *
 * @author LUCAS
 */
public class TelaPrincipalSDI extends javax.swing.JFrame {

    //ConexaoBD conecta = new ConexaoBD();
    FuncoesBanco f = new FuncoesBanco();
    public TelaPrincipalSDI() {
        initComponents();
        this.setTitle("SMES - StoffMalocoking Enterprise System");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TextoValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Botao_Buscar = new javax.swing.JButton();
        EscolhaAtributo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Caixa_Arquivo = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        Caixa_Admin = new javax.swing.JMenu();
        Login_Admin = new javax.swing.JMenuItem();
        Cadastro_Admin = new javax.swing.JMenuItem();
        Caixa_Cliente = new javax.swing.JMenu();
        Login_Cliente = new javax.swing.JMenuItem();
        Cadastro_Cliente = new javax.swing.JMenuItem();
        Caixa_Sobre = new javax.swing.JMenu();
        Botao_infor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setFocusable(false);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sem Título-1.png"))); // NOI18N

        TextoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoValorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busque o veículo mais adequado para você!");

        Botao_Buscar.setText("Buscar");
        Botao_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_BuscarActionPerformed(evt);
            }
        });

        EscolhaAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "Marca", "Modelo", "Cor" }));
        EscolhaAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaAtributoActionPerformed(evt);
            }
        });

        Caixa_Arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        Caixa_Arquivo.setText("Arquivo");

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Caixa_Arquivo.add(Sair);

        jMenuBar1.add(Caixa_Arquivo);

        Caixa_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        Caixa_Admin.setText("Admin");

        Login_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        Login_Admin.setText("Login");
        Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_AdminActionPerformed(evt);
            }
        });
        Caixa_Admin.add(Login_Admin);

        Cadastro_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        Cadastro_Admin.setText("Cadastrar");
        Cadastro_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_AdminActionPerformed(evt);
            }
        });
        Caixa_Admin.add(Cadastro_Admin);

        jMenuBar1.add(Caixa_Admin);

        Caixa_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        Caixa_Cliente.setText("Cliente");

        Login_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        Login_Cliente.setText("Login");
        Login_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ClienteActionPerformed(evt);
            }
        });
        Caixa_Cliente.add(Login_Cliente);

        Cadastro_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        Cadastro_Cliente.setText("Cadastrar");
        Cadastro_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ClienteActionPerformed(evt);
            }
        });
        Caixa_Cliente.add(Cadastro_Cliente);

        jMenuBar1.add(Caixa_Cliente);

        Caixa_Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        Caixa_Sobre.setText("Sobre");

        Botao_infor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        Botao_infor.setText("Informações");
        Botao_infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_inforActionPerformed(evt);
            }
        });
        Caixa_Sobre.add(Botao_infor);

        jMenuBar1.add(Caixa_Sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EscolhaAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(Botao_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscolhaAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Botao_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_AdminActionPerformed
        new TelaCadastroAdmSDI().setVisible(true);
    }//GEN-LAST:event_Cadastro_AdminActionPerformed

    private void Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_AdminActionPerformed
        new TelaLoginAdmSDI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login_AdminActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        //conecta.desconectar();
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void TextoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoValorActionPerformed

    private void Login_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ClienteActionPerformed
        new TelaLoginClienteSDI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login_ClienteActionPerformed

    private void Cadastro_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ClienteActionPerformed
        new TelaCadastroClienteSDI().setVisible(true);
    }//GEN-LAST:event_Cadastro_ClienteActionPerformed

    private void Botao_inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_inforActionPerformed
        new TelaSobreSDI().setVisible(true);
    }//GEN-LAST:event_Botao_inforActionPerformed

    private void Botao_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_BuscarActionPerformed
        String atributo = String.valueOf(EscolhaAtributo.getSelectedItem());
        String valor = TextoValor.getText();
        ArrayList lista_de_Veiculos = f.buscarVeiculosObject(atributo, valor);
        if(lista_de_Veiculos.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "Não há veículos com essa caracterítica!");
        }else{
        new TelaPesquisaSDI(lista_de_Veiculos).setVisible(true);
        }
    }//GEN-LAST:event_Botao_BuscarActionPerformed

    private void EscolhaAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolhaAtributoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Buscar;
    private javax.swing.JMenuItem Botao_infor;
    private javax.swing.JMenuItem Cadastro_Admin;
    private javax.swing.JMenuItem Cadastro_Cliente;
    private javax.swing.JMenu Caixa_Admin;
    private javax.swing.JMenu Caixa_Arquivo;
    private javax.swing.JMenu Caixa_Cliente;
    private javax.swing.JMenu Caixa_Sobre;
    private javax.swing.JComboBox<String> EscolhaAtributo;
    private javax.swing.JMenuItem Login_Admin;
    private javax.swing.JMenuItem Login_Cliente;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JTextField TextoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/car.png")));
    }
}
